# Generated by Django 5.0.2 on 2024-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0002_alter_donordetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='prov_no',
            field=models.CharField(max_length=50),
        ),
    ]
