# Generated by Django 5.0.2 on 2024-02-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0003_alter_donordetails_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
