# Generated by Django 5.0.2 on 2024-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0004_alter_donordetails_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetails',
            name='bloodgroup',
            field=models.CharField(max_length=10),
        ),
    ]
