# Generated by Django 5.0.2 on 2024-02-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0005_alter_requestdetails_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetails',
            name='prov_no',
            field=models.CharField(max_length=20),
        ),
    ]
