# Generated by Django 5.0.2 on 2024-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0006_alter_requestdetails_prov_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='confirm',
            field=models.CharField(max_length=10),
        ),
    ]
