# Generated by Django 5.0.2 on 2024-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0007_alter_donordetails_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donordetails',
            name='Email',
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='confirm',
            field=models.BooleanField(max_length=10),
        ),
    ]
